### ISSUE TITLE
Language select covered by Alert Box

### ISSUE THREAD

**Issue by kkoudelka** [cesko-digital/covid.gov.cz#118]
Language selector in the `Header` component is covered by the `Alert Box` component

![image](https://user-images.githubusercontent.com/25773348/98176412-6a56f480-1ef0-11eb-9188-022c951ce129.png)

**Comment by fra-iesus** [comment]
I suppose it's already "fixed" by the changes in the languages switch (it's not a dropdown menu anymore).
