### ISSUE TITLE
Display tooltip over truncated text

### ISSUE THREAD

**Issue by SonyPony** [cesko-digital/covid.gov.cz#255]
Display tooltip over truncated text. However due to contrast issue, it might be better to display the tooltip with a dark background.

![image](https://user-images.githubusercontent.com/8584106/98428497-12f88600-20a2-11eb-8f34-1ba469126dcb.png)

![image](https://user-images.githubusercontent.com/8584106/98428743-34a63d00-20a3-11eb-88a9-385f5051034b.png)

**Comment by vitkolos** [comment]
I assume this can't be achieved easily.
