### ISSUE TITLE
Chybný křížový odkaz v životní situaci Doma během nouzového stavu / Invalid link on page

### ISSUE THREAD

**Issue by SmallhillCZ** [cesko-digital/covid.gov.cz#283]
Na stránce URL https://covid.gov.cz/situace/stres-zvladani-dopadu-pandemie/doma-behem-nouzoveho-stavu kliknu na odkaz `Stres a zvládání dopadů pandemie >Duševní hygiena` a dostanu se na URL https://covid.gov.cz/situace/stres-zvladani-dopadu-pandemie/situace/stres-zvladani-dopadu-pandemie/dusevni-hygiena, která je 404.

When I click the link `Stres a zvládání dopadů pandemie >Duševní hygiena` on the URL https://covid.gov.cz/situace/stres-zvladani-dopadu-pandemie/doma-behem-nouzoveho-stavu kliknu na odkaz  I am taken to URL https://covid.gov.cz/situace/stres-zvladani-dopadu-pandemie/situace/stres-zvladani-dopadu-pandemie/dusevni-hygiena, which is 404.

**Comment by rostaklein** [comment]
Ahoj, diky za report!

Chyba byla nejspise na strane contentu, vsechno co se nachazi takhle "v tele" je prace naseho content tymu, tzn. tyto chyby prosim priste nahlasovat spise rovnou do slacku - `#p-informacni-web-content`.

Kazdopadke koukam, ze odkaz uz je opraven, tzn toto issue muzeme asi zavrit.
