### ISSUE TITLE
Navigation UX suggestion (mobile)

### ISSUE THREAD

**Issue by Martin5001** [cesko-digital/covid.gov.cz#284]
**Current design:**
To me it feels a bit distracting that when I open the navigation, the navbar logo seemingly "just disappears" as it gets covered by the navigation.
![Screenshot_20201108-175151_Chrome](https://user-images.githubusercontent.com/35201200/98471372-07b17180-21ec-11eb-860c-f6c1d0c3f285.jpg)

**Suggested design (as used on another gov.cz site):**
The logo placement is consistent (logo doesn't "disappear" when navigation is opened). And the change to lighter colour adds visual depth and makes it clear that the navigation is opened "on top", so the user doesn't feel disconnected even though the navigation still covers the whole page.
![Screenshot_20201108-175226_Chrome](https://user-images.githubusercontent.com/35201200/98471360-f700fb80-21eb-11eb-9e5d-738d6a3ead93.jpg)

**Comment by vitkolos** [comment]
Thanks for the suggestion, we will consult our UX designers about it.

**Comment by vitkolos** [comment]
We have it in Trello and will discuss it. Thanks again.
