### ISSUE TITLE
Google search result – "homepage_meta_title"

### ISSUE THREAD

**Issue by Martin5001** [cesko-digital/covid.gov.cz#334]
Vyhledávání Google nezobrazuje název webu (screenshot):
![20201112!UNITO-UNDERSCORE!105742](https://user-images.githubusercontent.com/35201200/98925381-34a8a180-24d6-11eb-991b-c1ea0d94ecc1.jpg)

┆Issue is synchronized with this [Trello card](https://trello.com/c/APiV9fXA) by [Unito](https://www.unito.io/learn-more)

**Comment by vitkolos** [comment]
This is probably already fixed in the code. Thanks for reporting it. We are currently trying to fix it on the Google Search Console level (we probably have to force Google to reindex the webpage). I will close it then.

**Comment by vitkolos** [comment]
It's hopefully fixed, Google seems OK to me. Closing.
