### ISSUE TITLE
UI – tlačítko "Všechna opatření" by mělo být odděleno od obsahu před

### ISSUE THREAD

**Issue by Martin5001** [cesko-digital/covid.gov.cz#388]
Je to drobnost, ale myslím, že by bylo přehlednější mít tlačítko "Všechna opatření" oddělené čarou stejně jako nadpis Aktuální opatření. Jinak to vypadá, že tlačítko patří k poslední položce.
![Screenshot!UNITO-UNDERSCORE!20201118-105521!UNITO-UNDERSCORE!Chrome](https://user-images.githubusercontent.com/35201200/99515052-bd1eba80-298c-11eb-80e6-46757a5fc9ef.jpg)

┆Issue is synchronized with this [Trello card](https://trello.com/c/Hu3jCMpf) by [Unito](https://www.unito.io/learn-more)

**Comment by rostaklein** [comment]
Ahoj :) Diky za report. Tato vec je urcite ke zvazeni nasich UX lidi :) Nicmene ti ted resi zavaznejsi problemy, tzn, myslim si, ze tohle v nejblizsi dobe fixovat nebudeme :) Kazdopadne kdyby se ti to chtelo fixnout, radi uvidime PR!
