### ISSUE TITLE
Bug: (mobile) image resizes when search in focus with keyboard opened

### ISSUE THREAD

**Issue by Martin5001** [cesko-digital/covid.gov.cz#389]
Pokud v mobilní verzi klepnu do vyhledávacího pole a zobrazí se klávesnice, zmenší se obrázek na stránce (viewport height/width?). Domnívám se, že to není záměr.
![Screenshot!UNITO-UNDERSCORE!20201118-131834!UNITO-UNDERSCORE!Chrome](https://user-images.githubusercontent.com/35201200/99530054-14c72100-29a1-11eb-95f5-a753810a0a97.jpg)
![Screenshot!UNITO-UNDERSCORE!20201118-131837!UNITO-UNDERSCORE!Chrome](https://user-images.githubusercontent.com/35201200/99530089-21e41000-29a1-11eb-9551-f1c92e237137.jpg)

┆Issue is synchronized with this [Trello card](https://trello.com/c/vRxEnr8L) by [Unito](https://www.unito.io/learn-more)

**Comment by rostaklein** [comment]
Ahoj :) Diky za report. Bohuzel se mi nepovedlo problem replikovat na androidu. Stejne tak si nemyslim, ze tohle v nejblizsi dobe fixneme, mame spoustu dalsi prace a zavaznejsich bugu :) Kazdopadne kdyby se ti to chtelo fixnout, radi uvidime PR!

**Comment by Martin5001** [comment]
Díky za odpověď :) Nemám žádné zkušenosti s GitHubem ze strany vývojáře, ani s live web vývojem, naučil jsem se jen sám nějaké základy frontendu, takže nevím, jestli bych s tím pomohl.

**Comment by redoper1** [comment]
@rostaklein zreplikovat se mi podařilo. Jde o to, že je tam u elementu, který obaluje te obrázek nastavena výška `55vh`, ale po otevření klávesnice se to okno prohlížeče zmenší o výšku té klávesnice a tím pádem se zmenší i ten obrázek. Nastává tedy otázka jak to lépe řešit.
