### ISSUE TITLE
Search některé věci nenajde

### ISSUE THREAD

**Issue by borekb** [cesko-digital/covid.gov.cz#433]
https://covid.gov.cz/hledat?q=airbnb:

<img width="1110" alt="Screen Shot 2020-12-15 at 21 19 53" src="https://user-images.githubusercontent.com/101152/102268201-4b01ad00-3f1b-11eb-9979-da429dfd3b32.png">

https://covid.gov.cz/situace/obchod-sluzby/ubytovani:

<img width="1110" alt="Screen Shot 2020-12-15 at 21 20 27" src="https://user-images.githubusercontent.com/101152/102268299-708eb680-3f1b-11eb-8ba3-21d865260179.png">

**Comment by vitkolos** [comment]
Už máme v Trellu, zavírám.
