### ISSUE TITLE
Button covers text in search box

### ISSUE THREAD

**Issue by kkoudelka** [cesko-digital/covid.gov.cz#94]
Search button covers the search query in the Search Box component.

![image](https://user-images.githubusercontent.com/25773348/98108742-65fcee00-1e94-11eb-8b78-eb09c332b41f.png)
![image](https://user-images.githubusercontent.com/25773348/98108780-71e8b000-1e94-11eb-95f7-543047c0ed42.png)

Probably just add `padding-right` to the `<input>` tag.

**Comment by Vesely** [comment]
https://github.com/cesko-digital/covid.gov.cz/pull/115
